name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Check flutter version
        run: flutter --version

      - name: Print Environment Details
        run: |
          echo "Flutter Channel: stable"
          flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false --dart-define buildDate=$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') --no-tree-shake-icons --base-href="/shopcom-admin/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
