name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Only run on pushes to the main branch

permissions:
  contents: read # Allow reading of the repository's contents
  pages: write   # Allow writing to the gh-pages branch
  id-token: write # Required for OpenID Connect (OIDC) authentication

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4 # Use actions/checkout@v4 for improved performance

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Use the stable Flutter channel
          cache: true # Enable caching for Flutter SDK

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            build/web/.last_build_id # Cache specific to Flutter web builds
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Check Flutter version
        run: flutter --version

      - name: Print Environment Details
        run: |
          echo "Flutter Channel: stable"
          flutter doctor -v # Use -v for verbose output

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web application
        run: |
          flutter build web --release \
            --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false \
            --no-tree-shake-icons \
            --base-href="/shopcom-admin/" # Matches your repository name

      - name: Debug Git configuration
        run: |
          git remote -v
          git branch -a
          ls -la build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided GitHub token
          publish_dir: build/web # Directory containing the built web application
          publish_branch: gh-pages # The branch to publish to
          force_orphan: true # Create a new branch with no history
          user_name: 'github-actions[bot]' # Commit author name
          user_email: 'github-actions[bot]@users.noreply.github.com' # Commit author email
          commit_message: 'Deploy Flutter web app to gh-pages' # Custom commit message